export type ProgressItem = {
  episodeId: string;
  episodeNumber: string;
  episodeTitle: string;
  episodeTypeClass: string;
  episodeTypeLabel: string;
  fanart: string;
  firstAired: string;
  fullTitle: string;
  logo: string;
  runtime: string;
  safe: string;
  screenshot: string;
  seasonId: string;
  seasonNumber: string;
  showId: string;
  topTitle: string;
  totalRuntime: string;
  type: 'show' | 'season' | 'episode';
  url: string;
};
