export type TmdbError = {
  code: number;
  status: number;
  message: string;
};

export const TmdbErrors = {
  1: { code: 1, status: 200, message: 'Success.' },
  2: { code: 2, status: 501, message: 'Invalid service: this service does not exist.' },
  3: { code: 3, status: 401, message: 'Authentication failed: You do not have permissions to access the service.' },
  4: { code: 4, status: 405, message: "Invalid format: This service doesn't exist in that format." },
  5: { code: 5, status: 422, message: 'Invalid parameters: Your request parameters are incorrect.' },
  6: { code: 6, status: 404, message: 'Invalid id: The pre-requisite id is invalid or not found.' },
  7: { code: 7, status: 401, message: 'Invalid API key: You must be granted a valid key.' },
  8: { code: 8, status: 403, message: 'Duplicate entry: The data you tried to submit already exists.' },
  9: { code: 9, status: 503, message: 'Service offline: This service is temporarily offline, try again later.' },
  10: { code: 10, status: 401, message: 'Suspended API key: Access to your account has been suspended, contact TMDB.' },
  11: { code: 11, status: 500, message: 'Internal error: Something went wrong, contact TMDB.' },
  12: { code: 12, status: 201, message: 'The item/record was updated successfully.' },
  13: { code: 13, status: 200, message: 'The item/record was deleted successfully.' },
  14: { code: 14, status: 401, message: 'Authentication failed.' },
  15: { code: 15, status: 500, message: 'Failed.' },
  16: { code: 16, status: 401, message: 'Device denied.' },
  17: { code: 17, status: 401, message: 'Session denied.' },
  18: { code: 18, status: 400, message: 'Validation failed.' },
  19: { code: 19, status: 406, message: 'Invalid accept header.' },
  20: { code: 20, status: 422, message: 'Invalid date range: Should be a range no longer than 14 days.' },
  21: { code: 21, status: 200, message: 'Entry not found: The item you are trying to edit cannot be found.' },
  22: { code: 22, status: 400, message: 'Invalid page: Pages start at 1 and max at 500. They are expected to be an integer.' },
  23: { code: 23, status: 400, message: 'Invalid date: Format needs to be YYYY-MM-DD.' },
  24: { code: 24, status: 504, message: 'Your request to the backend server timed out. Try again.' },
  25: { code: 25, status: 429, message: 'Your request count (#) is over the allowed limit of (40).' },
  26: { code: 26, status: 400, message: 'You must provide a username and password.' },
  27: { code: 27, status: 400, message: 'Too many append to response objects: The maximum number of remote calls is 20.' },
  28: { code: 28, status: 400, message: 'Invalid timezone: Please consult the documentation for a valid timezone.' },
  29: { code: 29, status: 400, message: 'You must confirm this action: Please provide a confirm=true parameter.' },
  30: { code: 30, status: 401, message: 'Invalid username and/or password: You did not provide a valid login.' },
  31: { code: 31, status: 401, message: 'Account disabled: Your account is no longer active. Contact TMDB if this is an error.' },
  32: { code: 32, status: 401, message: 'Email not verified: Your email address has not been verified.' },
  33: { code: 33, status: 401, message: 'Invalid request token: The request token is either expired or invalid.' },
  34: { code: 34, status: 404, message: 'The resource you requested could not be found.' },
  35: { code: 35, status: 401, message: 'Invalid token.' },
  36: { code: 36, status: 401, message: "This token hasn't been granted write permission by the user." },
  37: { code: 37, status: 404, message: 'The requested session could not be found.' },
  38: { code: 38, status: 401, message: "You don't have permission to edit this resource." },
  39: { code: 39, status: 401, message: 'This resource is private.' },
  40: { code: 40, status: 200, message: 'Nothing to update.' },
  41: { code: 41, status: 422, message: "This request token hasn't been approved by the user." },
  42: { code: 42, status: 405, message: 'This request method is not supported for this resource.' },
  43: { code: 43, status: 502, message: "Couldn't connect to the backend server." },
  44: { code: 44, status: 500, message: 'The ID is invalid.' },
  45: { code: 45, status: 403, message: 'This user has been suspended.' },
  46: { code: 46, status: 503, message: 'The API is undergoing maintenance. Try again later.' },
  47: { code: 47, status: 400, message: 'The input is not valid.' },
};
