name: 🚧 Build - Build sources

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-extension:
    name: 🔌 Build Extension
    runs-on: ubuntu-latest

    steps:
      - name: ⛙ Checkout branch ${{ github.ref }}
        uses: actions/checkout@v5

      - name: 🚧 Build
        uses: ./.github/actions/build
        with:
          trakt_production_id: ${{ secrets.VITE_TRAKT_PRODUCTION_ID }}
          trakt_production_secret: ${{ secrets.VITE_TRAKT_PRODUCTION_SECRET }}

          trakt_staging_id: ${{ secrets.VITE_TRAKT_STAGING_ID }}
          trakt_staging_secret: ${{ secrets.VITE_TRAKT_STAGING_SECRET }}

          tmdb_api_key: ${{ secrets.VITE_TMDB_API_KEY }}
          tmdb_read_token: ${{ secrets.VITE_TMDB_READ_TOKEN }}

          tvdb_api_key: ${{ secrets.VITE_TVDB_API_KEY }}

          simkl_client_id: ${{ secrets.VITE_SIMKL_CLIENT_ID }}
          simkl_client_secret: ${{ secrets.VITE_SIMKL_CLIENT_SECRET }}

  build-web:
    name: ☁️ Build Web
    runs-on: ubuntu-latest

    steps:
      - name: ⛙ Checkout branch ${{ github.ref }}
        uses: actions/checkout@v5

      - name: 🚧 Build
        uses: ./.github/actions/build
        with:
          script: 'build:web'

          trakt_production_id: ${{ secrets.VITE_TRAKT_PRODUCTION_ID }}
          trakt_production_secret: ${{ secrets.VITE_TRAKT_PRODUCTION_SECRET }}

          trakt_staging_id: ${{ secrets.VITE_TRAKT_STAGING_ID }}
          trakt_staging_secret: ${{ secrets.VITE_TRAKT_STAGING_SECRET }}

          tmdb_api_key: ${{ secrets.VITE_TMDB_API_KEY }}
          tmdb_read_token: ${{ secrets.VITE_TMDB_READ_TOKEN }}

          tvdb_api_key: ${{ secrets.VITE_TVDB_API_KEY }}

          simkl_client_id: ${{ secrets.VITE_SIMKL_CLIENT_ID }}
          simkl_client_secret: ${{ secrets.VITE_SIMKL_CLIENT_SECRET }}

  test:
    name: 🧪 Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: ⛙ Checkout branch ${{ github.ref }}
        uses: actions/checkout@v5

      - name: 🧱 Install
        uses: ./.github/actions/install

      - name: 🧪 Unit tests
        run: |
          # ================= 🧪 Unit tests =================
          pnpm run test:unit

  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest

    steps:
      - name: ⛙ Checkout branch ${{ github.ref }}
        uses: actions/checkout@v5

      - name: 🧱 Install
        uses: ./.github/actions/install

      - name: 🧹 Eslint
        run: |
          # =================  🧹 Eslint  =================
          pnpm run lint

      - name: 🪄 Stylelint
        run: |
          # =================  🪄 Stylelint  =================
          pnpm run style
